create table public."Reservas" (
  "ID Partida" serial not null,
  "Fecha ISO" date null,
  "Inicio" time without time zone null,
  "Fin" time without time zone null,
  "Pista" text null,
  "Nivel" public.nivel_enum null,
  "Nº Actuales" integer null,
  "Nº Faltantes" integer null,
  "Estado" public.estado_enum null,
  "ID Event" text null,
  "Fecha Creación" timestamp without time zone null,
  "Fecha Actualización" timestamp without time zone null,
  "Último Contacto" text null,
  "Actualización" text null,
  "Jugador 1" text null,
  "Jugador 2" text null,
  "Jugador 3" text null,
  "Jugador 4" text null,
  "Telefono 1" text null,
  "Telefono 2" text null,
  "Telefono 3" text null,
  "Telefono 4" text null,
  "Lista_invitados" text null,
  "Link Join" text null,
  "Link Delete" text null,
  "Link Cancel" text null,
  "1º Contacto" text null,
  "calendarID" text null,
  constraint Reservas_pkey primary key ("ID Partida"),
  constraint "Reservas_1º Contacto_fkey" foreign KEY ("1º Contacto") references "Jugadores" ("Teléfono") on update CASCADE on delete CASCADE
) TABLESPACE pg_default;